


development:
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 5
  database: myapp_db
  host: 127.0.0.1
  username: myapp_user
  password: 123456

production:
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 5
  database: exampledb
  host: 192.168.0.9
  username: geyiwu
  password: 123456
